exp:
  exp_name: null
  seed: 1
  torch_deterministic: true
  cuda: true
  wandb: false
  wandb_project_name: "cleanRL"
  wandb_entity: null
  capture_video: false
  env_id: null

optim:
  learning_rate: 2.5e-4
  anneal_lr: true
  max_grad_norm: 0.5
  target_kl: null

algo:
  gamma: 0.99
  gae_lambda: 0.95
  norm_adv: true
  clip_coef: 0.1
  clip_vloss: true
  ent_coef: 0.01
  vf_coef: 0.5

num_envs: 1 # 8
num_steps: 128
total_timesteps: 1e7
num_minibatches: 4
update_epochs: 4
