# defaults: 
# - buffer: base

name: "sac"

policy_kwargs:
  share_features_extractor: True

learning_rate: 0.0003 # ${r_tofloat:3e-4}

# 1m samples was too many (858GB) for 24GB.
buffer_size: ${r_toint:1e3}
# 120 * 50 epiisodes = 6000 steps
learning_starts: ${r_toint:1e3} # n env steps to collect transitions for before learning 

batch_size: 16
tau: 0.005
gamma: 0.99
train_freq: 1
gradient_steps: 1
action_noise: null

replay_buffer_class: null
# TODO fix for HER
# replay_buffer_kwargs: ${buffer}
replay_buffer_kwargs: null
optimize_memory_usage: false

# ent_coef: 'auto'
# target_entropy: 'auto'

target_update_interval: 1
use_sde: false
sde_sample_freq: -1
use_sde_at_warmup: false

stats_window_size: 100
tensorboard_log: null
seed: 0
device: 'auto'
_init_setup_model: true
