name: tqc

learning_rate: 3e-4
buffer_size: ${buffer.size} # 1000000
learning_starts: ${r_toint:1e4} 
batch_size: 256

tau: 0.005
gamma: 0.99
train_freq: 1
gradient_steps: 4 # default is 1 # UTD in DEAC paper
action_noise: null

replay_buffer_class: ${buffer.cls}
replay_buffer_kwargs: ${buffer.args}
optimize_memory_usage: false

ent_coef: auto_0.05
target_update_interval: 1
target_entropy: -7 # 'auto'

top_quantiles_to_drop_per_net: 0 # 2 is default

use_sde: false
sde_sample_freq: -1
use_sde_at_warmup: false

stats_window_size: 10
tensorboard_log: null

policy_kwargs: 
  share_features_extractor: true
  n_quantiles: 35  # 25 is default
  n_critics: 10 # from DEAC ... 2 is default

verbose: 0
seed: 0
device: "auto"
_init_setup_model: true

use_original_space: false
warmup_zero_action: false
