# HER hindsight experience replay buffer
# works with DQN, SAC, DDPG and TD3

name: "her"

# Available strategies (cf paper): future, final, episode
goal_selection_strategy: "future" # equivalent to GoalSelectionStrategy.FUTURE
n_sampled_goal: 4
buffer_size: ${algo.buffer_size}

# SB3 wants to initialize itself
# _target_: "stable_baselines3.HerReplayBuffer"
# _args_:
# goal_selection_strategy: ${.goal_selection_strategy}
# n_sampled_goal: ${.n_sampled_goal}
# buffer_size: ${.buffer_size}
